spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_plus?serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis-plus:
  type-enums-package: com.tcl.mp.enums
  configuration:
    use-generated-keys: true

