spring:
  datasource:
    url: jdbc:p6spy:mysql://localhost:3306/mybatis_plus?serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

mybatis-plus:
  type-enums-package: com.tcl.mp.enums
  configuration:
    use-generated-keys: true

